## Data config
train_src_corpus_path: ./data/train.ko.bpe
train_tgt_corpus_path: ./data/train.en.bpe
test_src_corpus_path: ./data/tst2016.ko.bpe
test_tgt_corpus_path: ./data/tst2016.en.bpe
src_vocab_path: ./data/bpe.ko.vocab
tgt_vocab_path: ./data/bpe.en.vocab
src_bpe_model_path: ./data/bpe.ko.model
tgt_bpe_model_path: ./data/bpe.en.model
## Training config
training_steps: 100000
warmup_step: 4000
max_len: 50
decoded_max_len: 150
batch_size: 40000
bos_idx: 2
eos_idx: 3
n_gpus: 8
model_path: transformer_ko2en.ckpt
## Model config 
num_layers: 6
num_heads: 8
hidden_dim: 512
linear_key_dim: 512
linear_value_dim: 512
ffn_dim: 2048
dropout: 0.1
vocab_size: 32000 
